travis:
  secure:
    BINSTAR_TOKEN: Y/WAGyIOAg9HvhKbhNnSd9RQdCLchYchP8Sp7eRkIU9Fozbpu/fnPTCf72nSCLsrpptZZ/C1oEYfhraugJKiGvLwpc7tXJH3DsR69pv6hXWaKUQkT8xHsUyhkh/K5X6PMN8n2syQ4C4FVcKMtLw+ybEx9eNjskjegTs/u8agWKBR4fKfPh2yD0eYhby2RL7A5/8rmHjez9lxz/1mCT+8Gc9r9yMx8Ogo2JRTUOF7VD79tk2QRXPttZoV7b0FOAR8EtNhYGkWBGzcuz0LNl+p02xIptwBAkvYZ/ZuQSCH5aPbjgQRZGikRWOHAcItLwciIo4Mr08Jiy5asy3rFcysrnPVkZeSt8HXIkUVymVEAwD6J5TF83vo76S9UVjncxaVyiPkRl1SyqEWJyas0MtMVRPD7TJ09oRmCHkjw/llPw+35ShQfuA/Myv5roVYmbgSuXVoKJYicIO8o6Gx8ltvt6GGwKcQ5vf+mqi8DNPPIySnFnw1QuRbZIzhYemmR4Ia7GyHyjuwBemithoE+arAZrBM7rRZtCvIvhwk3nVECeuE1c/e/ktQImDIzrOz0dFcVi/DTy4dl6PqJX5t2B12b5KNL38EJERnjwkzTvoBmpiS2lPIrTNFwGUsfC0YXKDxOgZKQOkC7cu9j+2N2oZSznzeH9DikOJRMLiCosmcFU4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
